// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"61490d21c6b58bf4372bdab9da244ea1c8ce5591b5fa007090683b86a83e0d0850cb4a968d2808d52dc2f037d3888bf849f63a3015de3914e21d4035bbd9c482"}}
];
